markdown: kramdown
highlighter: pygments
permalink: /Picstory/:year/:month/:day/:title.html
name: "Maxwell"
#markdown: kramdown

author: "Maxwell"
atom-baseurl: ""
disqus: ""

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /Picstory/archive.html
  - title: Tags
    class: fa fa-tags
    href: /Picstory/tags.html
  - title: About
    class: fa fa-user
    href: /Picstory/about.html
  - title: Gallery
    class: fa fa-film
    href: https://xueming1987.github.io
  - title: Subscribe
    class: fa fa-rss
    href: /Picstory/atom.xml

