name: "rusty shutter"
permalink: /:year/:month/:day/:title.html

author: "wayne"
atom-baseurl: "https://xiangblq.github.io/gallery/"
disqus: "gopherwood"

navigations:
  - title: Archive
    class: fa fa-list-ul
    href: /archive.html
  - title: Tags
    class: fa fa-tags
    href: /tags.html
  - title: About
    class: fa fa-user
    href: /about.html
  - title: Gallery
    class: fa fa-film
    href: https://xiangblq.github.io/gallery/
  - title: Subscribe
    class: fa fa-rss
    href: /atom.xml

